server:
  port: 80

file:
  upload-dir: /Users/user/Downloads/Danggeun/uploads

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: test-client-id
            client-secret: test-client-secret
            scope: [ email, profile ]
