server:
  port: 80

file:
  upload-dir: /Users/user/Downloads/Danggeun/uploads

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: test-client-id
            client-secret: test-client-secret
            scope: [ email, profile ]

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/danggeun
    username: postgres
    password: 1234

