server:
  port: 80


# application.yml

#file:
#  upload-dir: /Users/user/uploads

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/danggeun
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 9918

  jpa:
    hibernate:
      ddl-auto: update # 또는 create, none, validate 등
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect