server:
  port: 80

file:
  upload-dir: /Users/user/Downloads/Danggeun/uploads

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: test-client-id
            client-secret: test-client-secret
            scope: [ email, profile ]

  codec:
    max-in-memory-size: 2MB

openai:
  api-key: dummy-key #API 키 입력 필요 예시-> ${OPENAI_API_KEY}
  model: gpt-3.5-turbo        # 필요시 gpt-4o 등으로 변경