server:
  port: 8080
  address: 0.0.0.0

file:
  upload-dir: /home/ec2-user/uploads

aws:
  access-key-id: ${key}
  secret-access-key: ${key}
  region: ap-northeast-2
  s3:
    bucket-name: 2025-ipod


spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    cache: false

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${key}
            client-secret: ${key}
            scope: [ email, profile ]
            redirect-uri: "http://13.60.13.30.nip.io/login/oauth2/code/{registrationId}"
        provider:
          google:
            user-name-attribute: sub

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/danggeun
    username: postgres
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace



